### ISSUE TITLE
Smartmeterobis: No or too long answer from Serial Device after last request.

### ISSUE THREAD

**Issue by stallingerl** [webanizer/BlockPro#14]
err Error: No or too long answer from Serial Device after last request.
    at SerialResponseTransport.handleSerialTimeout (/home/Consolino2IPFS/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:292:36)
    at Timeout._onTimeout (/home/Consolino2IPFS/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:245:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
err Error: No or too long answer from Serial Device after last request.
    at SerialResponseTransport.handleSerialTimeout (/home/Consolino2IPFS/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:292:36)

**Comment by mrheat** [comment]
lets call it a "glitch"
